### ISSUE TITLE
BG Alert-Notifications show in snooze time.

### ISSUE THREAD

**Issue by AdrianLxM** [StephenBlackWasAlreadyTaken/xDrip#92]
BG Alert-Notifications show, even if in snooze time. Sound doesn't play.

I guess in file https://github.com/StephenBlackWasAlreadyTaken/xDrip/blob/master/app/src/main/java/com/eveningoutpost/dexdrip/UtilityModels/Notifications.java in **line 214**
` } else if ((userNotification != null) && (userNotification.timestamp >= ((new Date().getTime()) - (60000 * bg_snooze)))) {`

the ` >= ` should be a ` <= `.

Greetings, Adrian

**Comment by StephenBlackWasAlreadyTaken** [comment]
This one is actually intentional, I like having the alert showing threads whole time I am out of range but I don't want it making noise each time it updates, just while not snooze. This behavior is actually already changed though in the experimental repo (the entire bg alert system has been overhauled)

**Comment by AdrianLxM** [comment]
Ok, thanks for the quick reply, I'll be waiting for the experimental becoming master then and just do a quick workaround for my own device. Great work you are doing.
